package app.odyssey.engine

/**
 * Canon release v1 — the fixed national canon for milestone 0.
 *
 * Exactly two must-go places per state, 100 entries across all 50 states.
 * A state completes only when both of its ACTIVE entries are credited, so
 * state coverage and places coverage move at genuinely different rates.
 *
 * Generated data — edit the release, never the user's history. Changing the
 * canon means publishing v2 and re-folding; there is no migration path
 * because there is no derived state to migrate.
 */
object CanonV1 {

    val stateNames: Map<String, String> = mapOf(
        "AK" to "Alaska",
        "AL" to "Alabama",
        "AR" to "Arkansas",
        "AZ" to "Arizona",
        "CA" to "California",
        "CO" to "Colorado",
        "CT" to "Connecticut",
        "DE" to "Delaware",
        "FL" to "Florida",
        "GA" to "Georgia",
        "HI" to "Hawaii",
        "IA" to "Iowa",
        "ID" to "Idaho",
        "IL" to "Illinois",
        "IN" to "Indiana",
        "KS" to "Kansas",
        "KY" to "Kentucky",
        "LA" to "Louisiana",
        "MA" to "Massachusetts",
        "MD" to "Maryland",
        "ME" to "Maine",
        "MI" to "Michigan",
        "MN" to "Minnesota",
        "MO" to "Missouri",
        "MS" to "Mississippi",
        "MT" to "Montana",
        "NC" to "North Carolina",
        "ND" to "North Dakota",
        "NE" to "Nebraska",
        "NH" to "New Hampshire",
        "NJ" to "New Jersey",
        "NM" to "New Mexico",
        "NV" to "Nevada",
        "NY" to "New York",
        "OH" to "Ohio",
        "OK" to "Oklahoma",
        "OR" to "Oregon",
        "PA" to "Pennsylvania",
        "RI" to "Rhode Island",
        "SC" to "South Carolina",
        "SD" to "South Dakota",
        "TN" to "Tennessee",
        "TX" to "Texas",
        "UT" to "Utah",
        "VA" to "Virginia",
        "VT" to "Vermont",
        "WA" to "Washington",
        "WI" to "Wisconsin",
        "WV" to "West Virginia",
        "WY" to "Wyoming",
    )

    val release: CanonRelease = CanonRelease(
        version = 1,
        entries = listOf(
            CanonEntry(
                placeId = "us-al-uss-alabama",
                usState = "AL",
                name = "USS Alabama Battleship Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(30.6819, -88.0147),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-al-civil-rights",
                usState = "AL",
                name = "Birmingham Civil Rights Institute",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(33.5157, -86.8149),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 800.0,
            ),
            CanonEntry(
                placeId = "us-ak-denali",
                usState = "AK",
                name = "Denali National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(63.1148, -151.1926),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-ak-glacier-bay",
                usState = "AK",
                name = "Glacier Bay National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(58.6658, -136.9002),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-az-grand-canyon",
                usState = "AZ",
                name = "Grand Canyon South Rim",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(36.0544, -112.1401),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 12000.0,
            ),
            CanonEntry(
                placeId = "us-az-antelope-canyon",
                usState = "AZ",
                name = "Antelope Canyon",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(36.8619, -111.3743),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-ar-hot-springs",
                usState = "AR",
                name = "Hot Springs National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(34.5117, -93.0538),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 6000.0,
            ),
            CanonEntry(
                placeId = "us-ar-crystal-bridges",
                usState = "AR",
                name = "Crystal Bridges Museum",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(36.3808, -94.2043),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-ca-yosemite",
                usState = "CA",
                name = "Yosemite Valley",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(37.7456, -119.5936),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-ca-golden-gate",
                usState = "CA",
                name = "Golden Gate Bridge",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(37.8199, -122.4783),
                minDwellSeconds = 1800,
                geofenceRadiusMeters = 2500.0,
            ),
            CanonEntry(
                placeId = "us-co-rocky-mountain",
                usState = "CO",
                name = "Rocky Mountain National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(40.3428, -105.6836),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-co-mesa-verde",
                usState = "CO",
                name = "Mesa Verde National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(37.2309, -108.4618),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-ct-mystic-seaport",
                usState = "CT",
                name = "Mystic Seaport Museum",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.3626, -71.9662),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-ct-yale-art",
                usState = "CT",
                name = "Yale University Art Gallery",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.3083, -72.9315),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 800.0,
            ),
            CanonEntry(
                placeId = "us-de-winterthur",
                usState = "DE",
                name = "Winterthur Museum & Garden",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(39.8043, -75.5985),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 2500.0,
            ),
            CanonEntry(
                placeId = "us-de-cape-henlopen",
                usState = "DE",
                name = "Cape Henlopen State Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.7862, -75.093),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 5000.0,
            ),
            CanonEntry(
                placeId = "us-fl-everglades",
                usState = "FL",
                name = "Everglades National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(25.2866, -80.8987),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-fl-kennedy-space",
                usState = "FL",
                name = "Kennedy Space Center",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(28.5729, -80.649),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 6000.0,
            ),
            CanonEntry(
                placeId = "us-ga-savannah",
                usState = "GA",
                name = "Savannah Historic District",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(32.0782, -81.0912),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-ga-mlk-historic",
                usState = "GA",
                name = "MLK Jr. National Historical Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(33.7556, -84.3733),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-hi-volcanoes",
                usState = "HI",
                name = "Hawai'i Volcanoes National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(19.4194, -155.2885),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-hi-pearl-harbor",
                usState = "HI",
                name = "Pearl Harbor Memorial",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(21.3649, -157.9399),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 2500.0,
            ),
            CanonEntry(
                placeId = "us-id-craters-moon",
                usState = "ID",
                name = "Craters of the Moon",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.4167, -113.5167),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-id-sawtooth",
                usState = "ID",
                name = "Sawtooth National Rec. Area",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(44.16, -114.93),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-il-art-institute",
                usState = "IL",
                name = "Art Institute of Chicago",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.8796, -87.6237),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 800.0,
            ),
            CanonEntry(
                placeId = "us-il-cloud-gate",
                usState = "IL",
                name = "Millennium Park & Cloud Gate",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.8826, -87.6226),
                minDwellSeconds = 1800,
                geofenceRadiusMeters = 800.0,
            ),
            CanonEntry(
                placeId = "us-in-motor-speedway",
                usState = "IN",
                name = "Indianapolis Motor Speedway",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(39.795, -86.2347),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-in-indiana-dunes",
                usState = "IN",
                name = "Indiana Dunes National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.6533, -87.0524),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 12000.0,
            ),
            CanonEntry(
                placeId = "us-ia-field-of-dreams",
                usState = "IA",
                name = "Field of Dreams",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(42.4711, -90.9268),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-ia-effigy-mounds",
                usState = "IA",
                name = "Effigy Mounds National Monument",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.0908, -91.1868),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 6000.0,
            ),
            CanonEntry(
                placeId = "us-ks-tallgrass",
                usState = "KS",
                name = "Tallgrass Prairie Preserve",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.4322, -96.5583),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 12000.0,
            ),
            CanonEntry(
                placeId = "us-ks-nelson-atkins",
                usState = "KS",
                name = "Nelson-Atkins Museum",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(39.0451, -94.5807),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 800.0,
            ),
            CanonEntry(
                placeId = "us-ky-mammoth-cave",
                usState = "KY",
                name = "Mammoth Cave National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(37.1862, -86.1),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 12000.0,
            ),
            CanonEntry(
                placeId = "us-ky-churchill-downs",
                usState = "KY",
                name = "Churchill Downs",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.2027, -85.7708),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-la-french-quarter",
                usState = "LA",
                name = "French Quarter",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(29.9584, -90.0644),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 2000.0,
            ),
            CanonEntry(
                placeId = "us-la-oak-alley",
                usState = "LA",
                name = "Oak Alley Plantation",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(30.0055, -90.8817),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-me-acadia",
                usState = "ME",
                name = "Acadia National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(44.3386, -68.2733),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-me-portland-head",
                usState = "ME",
                name = "Portland Head Light",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.6231, -70.2078),
                minDwellSeconds = 1800,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-md-fort-mchenry",
                usState = "MD",
                name = "Fort McHenry",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(39.2639, -76.58),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-md-assateague",
                usState = "MD",
                name = "Assateague Island",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.2497, -75.1519),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 10000.0,
            ),
            CanonEntry(
                placeId = "us-ma-freedom-trail",
                usState = "MA",
                name = "Boston Freedom Trail",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(42.3601, -71.0589),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-ma-cape-cod",
                usState = "MA",
                name = "Cape Cod National Seashore",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.925, -70.02),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-mi-pictured-rocks",
                usState = "MI",
                name = "Pictured Rocks Lakeshore",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(46.5522, -86.34),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-mi-mackinac",
                usState = "MI",
                name = "Mackinac Island",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(45.8492, -84.6189),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 5000.0,
            ),
            CanonEntry(
                placeId = "us-mn-boundary-waters",
                usState = "MN",
                name = "Boundary Waters Canoe Area",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(47.95, -91.5),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 30000.0,
            ),
            CanonEntry(
                placeId = "us-mn-split-rock",
                usState = "MN",
                name = "Split Rock Lighthouse",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(47.2003, -91.3672),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 2000.0,
            ),
            CanonEntry(
                placeId = "us-ms-vicksburg",
                usState = "MS",
                name = "Vicksburg National Military Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(32.3465, -90.8546),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 6000.0,
            ),
            CanonEntry(
                placeId = "us-ms-natchez-trace",
                usState = "MS",
                name = "Natchez Trace Parkway",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(32.2988, -90.9084),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-mo-gateway-arch",
                usState = "MO",
                name = "Gateway Arch",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.6247, -90.1848),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-mo-ozarks",
                usState = "MO",
                name = "Ozark National Scenic Riverways",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(37.1833, -91.25),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-mt-glacier",
                usState = "MT",
                name = "Glacier National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(48.7596, -113.787),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-mt-little-bighorn",
                usState = "MT",
                name = "Little Bighorn Battlefield",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(45.5703, -107.4292),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 5000.0,
            ),
            CanonEntry(
                placeId = "us-ne-chimney-rock",
                usState = "NE",
                name = "Chimney Rock",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.7036, -103.3494),
                minDwellSeconds = 1800,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-ne-henry-doorly",
                usState = "NE",
                name = "Henry Doorly Zoo",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.2278, -95.9247),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-nv-las-vegas-strip",
                usState = "NV",
                name = "Las Vegas Strip",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(36.1147, -115.1728),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-nv-valley-of-fire",
                usState = "NV",
                name = "Valley of Fire State Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(36.4816, -114.5253),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 12000.0,
            ),
            CanonEntry(
                placeId = "us-nh-mount-washington",
                usState = "NH",
                name = "Mount Washington",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(44.2705, -71.3033),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 6000.0,
            ),
            CanonEntry(
                placeId = "us-nh-franconia-notch",
                usState = "NH",
                name = "Franconia Notch",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(44.15, -71.6833),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 8000.0,
            ),
            CanonEntry(
                placeId = "us-nj-liberty-park",
                usState = "NJ",
                name = "Liberty State Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(40.705, -74.0553),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-nj-cape-may",
                usState = "NJ",
                name = "Cape May Historic District",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.9351, -74.906),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 2500.0,
            ),
            CanonEntry(
                placeId = "us-nm-carlsbad",
                usState = "NM",
                name = "Carlsbad Caverns",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(32.1479, -104.5567),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 10000.0,
            ),
            CanonEntry(
                placeId = "us-nm-white-sands",
                usState = "NM",
                name = "White Sands National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(32.7791, -106.1717),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-ny-statue-liberty",
                usState = "NY",
                name = "Statue of Liberty",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(40.6892, -74.0445),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 2000.0,
            ),
            CanonEntry(
                placeId = "us-ny-niagara-falls",
                usState = "NY",
                name = "Niagara Falls State Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.0828, -79.0742),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-nc-blue-ridge",
                usState = "NC",
                name = "Blue Ridge Parkway",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(35.5951, -82.5515),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-nc-outer-banks",
                usState = "NC",
                name = "Cape Hatteras Lighthouse",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(35.2508, -75.5288),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-nd-theodore-roosevelt",
                usState = "ND",
                name = "Theodore Roosevelt National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(46.979, -103.5387),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-nd-knife-river",
                usState = "ND",
                name = "Knife River Indian Villages",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(47.3372, -101.3838),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 5000.0,
            ),
            CanonEntry(
                placeId = "us-oh-rock-hall",
                usState = "OH",
                name = "Rock & Roll Hall of Fame",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.5085, -81.6954),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-oh-cuyahoga",
                usState = "OH",
                name = "Cuyahoga Valley National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.2808, -81.5678),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-ok-omm",
                usState = "OK",
                name = "Oklahoma City National Memorial",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(35.4728, -97.517),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-ok-wichita-mtns",
                usState = "OK",
                name = "Wichita Mountains Refuge",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(34.73, -98.7),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-or-crater-lake",
                usState = "OR",
                name = "Crater Lake National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(42.9446, -122.109),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-or-columbia-gorge",
                usState = "OR",
                name = "Columbia River Gorge",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(45.5762, -122.1158),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-pa-independence",
                usState = "PA",
                name = "Independence Hall",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(39.9489, -75.15),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-pa-gettysburg",
                usState = "PA",
                name = "Gettysburg National Military Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(39.8117, -77.2311),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 8000.0,
            ),
            CanonEntry(
                placeId = "us-ri-the-breakers",
                usState = "RI",
                name = "The Breakers, Newport",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.4696, -71.2986),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-ri-block-island",
                usState = "RI",
                name = "Block Island",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(41.1683, -71.5783),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 6000.0,
            ),
            CanonEntry(
                placeId = "us-sc-charleston",
                usState = "SC",
                name = "Charleston Historic District",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(32.7765, -79.9311),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-sc-fort-sumter",
                usState = "SC",
                name = "Fort Sumter",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(32.7522, -79.8747),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-sd-mount-rushmore",
                usState = "SD",
                name = "Mount Rushmore",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.8791, -103.4591),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-sd-badlands",
                usState = "SD",
                name = "Badlands National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.8554, -102.3397),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-tn-great-smoky",
                usState = "TN",
                name = "Great Smoky Mountains",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(35.6532, -83.507),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-tn-graceland",
                usState = "TN",
                name = "Graceland",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(35.0478, -90.026),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-tx-the-alamo",
                usState = "TX",
                name = "The Alamo",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(29.426, -98.4861),
                minDwellSeconds = 2700,
                geofenceRadiusMeters = 1200.0,
            ),
            CanonEntry(
                placeId = "us-tx-big-bend",
                usState = "TX",
                name = "Big Bend National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(29.2498, -103.2502),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 30000.0,
            ),
            CanonEntry(
                placeId = "us-ut-zion",
                usState = "UT",
                name = "Zion National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(37.2982, -113.0263),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-ut-arches",
                usState = "UT",
                name = "Arches National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.7331, -109.5925),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-vt-shelburne",
                usState = "VT",
                name = "Shelburne Museum",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(44.3714, -73.2262),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 1500.0,
            ),
            CanonEntry(
                placeId = "us-vt-stowe",
                usState = "VT",
                name = "Stowe & Mount Mansfield",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(44.5438, -72.8143),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 8000.0,
            ),
            CanonEntry(
                placeId = "us-va-monticello",
                usState = "VA",
                name = "Monticello",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.0088, -78.4529),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 2000.0,
            ),
            CanonEntry(
                placeId = "us-va-shenandoah",
                usState = "VA",
                name = "Shenandoah National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(38.53, -78.35),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 25000.0,
            ),
            CanonEntry(
                placeId = "us-wa-mount-rainier",
                usState = "WA",
                name = "Mount Rainier National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(46.8523, -121.7603),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-wa-pike-place",
                usState = "WA",
                name = "Pike Place Market",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(47.6097, -122.3422),
                minDwellSeconds = 1800,
                geofenceRadiusMeters = 800.0,
            ),
            CanonEntry(
                placeId = "us-wv-new-river-gorge",
                usState = "WV",
                name = "New River Gorge National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(37.9393, -81.0668),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 15000.0,
            ),
            CanonEntry(
                placeId = "us-wv-harpers-ferry",
                usState = "WV",
                name = "Harpers Ferry",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(39.3256, -77.7386),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 3000.0,
            ),
            CanonEntry(
                placeId = "us-wi-apostle-islands",
                usState = "WI",
                name = "Apostle Islands Lakeshore",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(46.96, -90.66),
                minDwellSeconds = 5400,
                geofenceRadiusMeters = 20000.0,
            ),
            CanonEntry(
                placeId = "us-wi-taliesin",
                usState = "WI",
                name = "Taliesin",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.1409, -90.0698),
                minDwellSeconds = 3600,
                geofenceRadiusMeters = 2000.0,
            ),
            CanonEntry(
                placeId = "us-wy-yellowstone",
                usState = "WY",
                name = "Yellowstone National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(44.428, -110.5885),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 40000.0,
            ),
            CanonEntry(
                placeId = "us-wy-grand-teton",
                usState = "WY",
                name = "Grand Teton National Park",
                lifecycle = Lifecycle.ACTIVE,
                centroid = LatLng(43.7904, -110.6818),
                minDwellSeconds = 7200,
                geofenceRadiusMeters = 25000.0,
            ),
        ),
    )

    fun stateName(code: String): String = stateNames[code] ?: code
}
